### ISSUE TITLE
Game start issue.

### ISSUE THREAD

**Issue by MinecraftAdmin** [dumbninja22/UHNSBugTracker#1]
Hello. Arena setup is flawless. I get this error on starting a game after arena is fully set up.

http://pastebin.com/raw.php?i=kpkiPPpS

My support code: http://puu.sh/j5JWa/c0cac89114.png

**Comment by dumbninja22** [comment]
Ok I read through all the logs and everything. Thanks for the detailed report.

First, what is your Spigot version? The support code is saying 1.8.7 but the log is saying 1.8.0.
Second, if you have MySQL enabled, do you also have Bungeecord enabled?
I would suggest, from looking at the logs, that one of your locations where the player will eventually be teleported is null. Try recreating the arena, maybe in flat file mode for now. If you didn't have Bungeecord enabled in config.yml then enable it and recreate the arena in MySQL.

**Comment by MinecraftAdmin** [comment]
Hi. Sorry for the late reply.

I set up the arenas again and made sure to define proper spawn points.
I do not have MySQL enabled. I dont have BungeeCord enabled.

Here is my console log
http://pastebin.com/Bu8vC30V

**Comment by MinecraftAdmin** [comment]
I set up the arena again after turning on Sql and properly setting up the sql tables. This is the console error log on game start. Let me know what other information you need as I would like to launch this server soon!

http://pastebin.com/YkUR7sP0

**Comment by MinecraftAdmin** [comment]
Maybe you need to build this against WorldGuard 6? Im not sure, as I am not a developer.

**Comment by dumbninja22** [comment]
OK if you want to use SQL you must have a proper Bungeecord server. The plugin will try to find the server's name using the whole plugin messaging thing so it would be best if we just get flat-file to work first.

First thing I suggest doing is deleting all the files in the Ultimate Hide N Seek folder.

Then re-make the arena, making sure to define the disguise blocks. Try only one or two simple blocks like dirt and stone. Only one spawn point is supported.

Let me know what happens. If you want me to come on your server I can.
