### ISSUE TITLE
Block name translations

### ISSUE THREAD

**Issue by JHXSMatthew** [dumbninja22/UHNSBugTracker#10]
Currently I am running this plugin on Chinese server.
Some people cannot understand English.
So they do not under stand "Monster Egg "

At this stage , would you mind using some language files? or Is there a way to show it into Chinese.

![image](https://cloud.githubusercontent.com/assets/11565658/9834730/9b8b8aac-5a0b-11e5-8f99-44458a87fb7b.png)

**Comment by JHXSMatthew** [comment]
Hope give you some ideas
https://www.spigotmc.org/wiki/the-chat-component-api/

**Comment by dumbninja22** [comment]
Adding in 1.5.0
