### ISSUE TITLE
Join notification On bungeeMode

### ISSUE THREAD

**Issue by JHXSMatthew** [dumbninja22/UHNSBugTracker#11]
The joinMessage event should be canceled when player join the server under BungeeMode.

![image](https://cloud.githubusercontent.com/assets/11565658/9834743/cfc4c658-5a0b-11e5-9999-ae71df4bfae4.png)

**Comment by dumbninja22** [comment]
Join or leave message?

**Comment by JHXSMatthew** [comment]
Sorry, leave message ;)

**Comment by dumbninja22** [comment]
Shouldn't be too hard. Thanks for your reports.

**Comment by JHXSMatthew** [comment]
:)

**Comment by dumbninja22** [comment]
Added in 1.4.6
