### ISSUE TITLE
ScoreBoard Flickering while Gaming

### ISSUE THREAD

**Issue by JHXSMatthew** [dumbninja22/UHNSBugTracker#12]
You may add option to send Action bar message while gaming and disable score updating per second.
That is really flickering 

PS:

Action bar sending code:

	public static void sendActionBar(Player p, String msg) {
		IChatBaseComponent cbc = ChatSerializer.a("{\"text\": \"" + msg + "\"}");
		PacketPlayOutChat ppoc = new PacketPlayOutChat(cbc, (byte) 2);
		((CraftPlayer) p).getHandle().playerConnection.sendPacket(ppoc);
	}

**Comment by dumbninja22** [comment]
I am keeping the scoreboard. Issue will be fixed when I fix the pregame flickering since I can use same code.

**Comment by dumbninja22** [comment]
Will be fixed in 1.5.0.
