### ISSUE TITLE
Suggestion: Display name color change respect to team while gaming

### ISSUE THREAD

**Issue by JHXSMatthew** [dumbninja22/UHNSBugTracker#13]
You may change players display name color to their team thus it's better to see who are seekers and who are hiders.

![image](https://cloud.githubusercontent.com/assets/11565658/9834751/6bc0040a-5a0c-11e5-801b-7a919a8e0cec.png)

**Comment by dumbninja22** [comment]
Added some code for this in 1.4.6, but it doesn't seem to work for me.

**Comment by dumbninja22** [comment]
Will be added in 1.5.0.
