### ISSUE TITLE
Game starts when only one player

### ISSUE THREAD

**Issue by JHXSMatthew** [dumbninja22/UHNSBugTracker#15]
![image](https://cloud.githubusercontent.com/assets/11565658/9834772/758fe60c-5a0d-11e5-8785-85709884f159.png)

**Comment by dumbninja22** [comment]
Hmmm. Are you using /hns start?
If not, try /hns setminplayers <arena name> <number>

**Comment by JHXSMatthew** [comment]
No,  I did not.
And it does not work with 
 /hns setminplayers [arena name] [number]


Any idea from this entry ?

![image](https://cloud.githubusercontent.com/assets/11565658/9834820/4a2c964c-5a10-11e5-9370-198681bfff0c.png)

**Comment by dumbninja22** [comment]
No idea there, sorry. Will have a look.

**Comment by dumbninja22** [comment]
Found the issue - fixing now. Should be patched on 1.5.0.
