### ISSUE TITLE
Hider is Killed and die. Not becoming Seekers 

### ISSUE THREAD

**Issue by JHXSMatthew** [dumbninja22/UHNSBugTracker#17]
No error messages were there.
Just die and can click respawn

picture is I am in lobby (after respawn) and I am still disguising as a block.

![image](https://cloud.githubusercontent.com/assets/11565658/9834800/7bd240b2-5a0f-11e5-90ba-9a60174b36ae.png)
![Uploading image.png…]()

**Comment by dumbninja22** [comment]
1) How did you die?
2) Did someone do /kill
3) Does this always happen?

**Comment by JHXSMatthew** [comment]
1> Killed by a seeker with sword
2> No
3> No, sometimes.

**Comment by dumbninja22** [comment]
I will guess that this is somehow related to the other issues. In Java, if an uncaught error is released, the rest of the code won't execute.

**Comment by dumbninja22** [comment]
Should be fixed in 1.4.9
