### ISSUE TITLE
Arena don't reset

### ISSUE THREAD

**Issue by llSimsll** [dumbninja22/UHNSBugTracker#18]
When i /stop the server, ALL my arenas disappear from the MySQL table.

**Comment by llSimsll** [comment]
When i /stop the server, ALL my arenas disappear from the MySQL table.

**Comment by dumbninja22** [comment]
Could I get the code from /hns support

**Comment by llSimsll** [comment]
Could you get it to output in a file? It's really annoying to copy manually.
LD8.65-PL3.64-VLTNULL-UHN1.4.6-MCv1_8_R3-BNGE_true-SQL_true

**Comment by dumbninja22** [comment]
1) You can always send me a screenshot
2) Your code checks out. It should be working. This leaves only one last probable cause:
3) Could I get a pic/screenshot of your SQL table for HNS Arenas?

**Comment by llSimsll** [comment]
When one of two player dies, he gets ported to the mainlobby. Game won't reset. When the time runs out, the remaining player stays where he is, and don't get ported to mainlobby.

![hns5](https://cloud.githubusercontent.com/assets/243194/10095703/ef80b812-636b-11e5-9d42-774497a8828e.png)
![hns6](https://cloud.githubusercontent.com/assets/243194/10095704/f32f176a-636b-11e5-9de7-52413fb926b7.png)
![hns7](https://cloud.githubusercontent.com/assets/243194/10095719/16bd3c98-636c-11e5-8446-71c0ab80ec71.png)
![hns8](https://cloud.githubusercontent.com/assets/243194/10095720/19a6c74e-636c-11e5-9a5c-4ec18ae2951c.png)

**Comment by dumbninja22** [comment]
Any errors?

**Comment by llSimsll** [comment]
No errors. Also when I leave an arena, I don't get spawned back to mainlobby. I stay in the arena.

**Comment by dumbninja22** [comment]
The you died error should have been fixed in 1.4.9
