### ISSUE TITLE
Scoreboard Issue by IISimsII

### ISSUE THREAD

**Issue by dumbninja22** [dumbninja22/UHNSBugTracker#19]
![hns](https://cloud.githubusercontent.com/assets/243194/9913594/f0d644a8-5cad-11e5-8acd-597e862fb843.png)

**Comment by dumbninja22** [comment]
I think this is impossible to happen. Restart the server completely when you save the new config.

**Comment by llSimsll** [comment]
It happened twice, so impossible no. I did save, restart and join the game.
![hns1](https://cloud.githubusercontent.com/assets/243194/9938794/59d827dc-5d67-11e5-98ac-f292346120c5.png)

Now the arena don't disappear from database, but the game doesn't restart still.

**Comment by llSimsll** [comment]
![hns2](https://cloud.githubusercontent.com/assets/243194/9939269/c21a1538-5d69-11e5-9d72-ea4aac53ab20.png)

Fresh server restart, can't click sign.

**Comment by dumbninja22** [comment]
OK. I see economy related errors so I suggest installing Vault and an economy plugin to see if that can help.

**Comment by llSimsll** [comment]
Any particular recommendations? 
After a few secs after clicking the sign, it says  the arena has no blocks set up. But I most certain did set up blocks for the arena.

**Comment by dumbninja22** [comment]
Vault and Craftconomy.

**Comment by llSimsll** [comment]
I would rather not have an economy system, but I'll give at try, just for bug-tracking purpose.

**Comment by dumbninja22** [comment]
Yeah. If it works with the economy I will go ahead and fix it because then I know its an economy issue.

**Comment by llSimsll** [comment]
[18:55:53 WARN]: [Ultimate_Hide_N_Seek] Task #35 for Ultimate_Hide_N_Seek v1.4.6
 generated an exception
java.lang.NullPointerException
        at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.currencyNameP
lural(Economy_Craftconomy3.java:115) ~[?:?]
        at com.dumbninja22.ultimatehidenseek.Minigame.stop(Minigame.java:667) ~[
?:?]
        at com.dumbninja22.ultimatehidenseek.ninjagamesAPI.ArenaManager.stopAren
a(ArenaManager.java:688) ~[?:?]
        at com.dumbninja22.ultimatehidenseek.DelayEffectII$1.run(DelayEffectII.j
ava:27) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java
:71) ~[Spigot.jar:git-Spigot-0359393-9cd1111]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHea
rtbeat(CraftScheduler.java:350) [Spigot.jar:git-Spigot-0359393-9cd1111]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:7
22) [Spigot.jar:git-Spigot-0359393-9cd1111]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
74) [Spigot.jar:git-Spigot-0359393-9cd1111]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
53) [Spigot.jar:git-Spigot-0359393-9cd1111]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:556) [Spigot.jar:git-Spigot-0359393-9cd1111]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]

**Comment by dumbninja22** [comment]
Another economy error. This one has to do with not having setup a currency name.

**Comment by llSimsll** [comment]
I really didn't read it, sorry.

**Comment by llSimsll** [comment]
Okay, did compile a fresh spigot server. Game don't reset, clicking sign -> The games has already started, and we're back at the first error i posted. Installed Vault and Craftconomy, now it works perfect!

**Comment by llSimsll** [comment]
I tried removing the economy plugin, now this happens. This is on the new server, no other plugins or anything. HNS running fresh with default settings.
![hns3](https://cloud.githubusercontent.com/assets/243194/9941715/6f3a1bfc-5d77-11e5-8878-6aa734d31272.png)

**Comment by dumbninja22** [comment]
So basically with Vault and economy everything is perfect?

**Comment by llSimsll** [comment]
Yes, with Vault and Economy everything's fine. Working great. But as I said, I would rather not use economy at all :)

**Comment by dumbninja22** [comment]
Alright then. That explains a lot. All my debugging is on my server and Vault + Craftconomy is always on. So now I should fix this - I don't think it will be too hard.

**Comment by llSimsll** [comment]
Sounds terrific, looking forward to get playing! Thanks for the great and patient support! Really appreciated. :+1:

**Comment by dumbninja22** [comment]
Did the latest update fix it?

**Comment by llSimsll** [comment]
Sorry, but no changes, same errors :(

**Comment by dumbninja22** [comment]
Repost the errors please.

**Comment by llSimsll** [comment]
The arena resets selected hider-blocks still. Is it possible to remove the shop selector, when vault is not installed?

![hns4](https://cloud.githubusercontent.com/assets/243194/10012986/8c7339a8-610d-11e5-93a9-3ec88538c7d1.png)

**Comment by dumbninja22** [comment]
Posted a new update. Shop selector was never shown in the inventory without Vault. Are you sure you don't have Vault installed? If you have any more problems I want to see your plugin list.
