### ISSUE TITLE
Arena overlaps another

### ISSUE THREAD

**Issue by MehanoPT** [dumbninja22/UHNSBugTracker#2]
Hello!
Sorry any English error.
I followed the steps in the plugin page to create an arena.
This arena was working well.
Then I created another arena, following the steps in the plugin page.
After clicking on the lobby sign I get the following message:
"You are unable to join this arena because it overlaps another arena. Please inform the admin of this error."
My first arena (working well) is "Villa" and my second is "Hotel".

Here is the config dumped by the plugin (HNSarenas.yml)

maxPlayers:
  Villa: 16
  Hotel: 16
mainLobby:
  Villa: lobby:-77:25:124
  Hotel: lobby:-77:25:124
arenaLobby:
  Villa: HNS_Villa:-130:66:713
  Hotel: HNS_Hotel:-125:75:723
boundsLow:
  Villa: HNS_Villa:-192:63:717
  Hotel: HNS_Hotel:-67:63:765
boundsHigh:
  Villa: HNS_Villa:-65:116:844
  Hotel: HNS_Hotel:-160:105:672
maxSeekers:
  Villa: 2
  Hotel: 2
HNSArenas:
  Villa: HNS_Villa:-130:66:719
  Hotel: HNS_Hotel:-125:75:723

The support code is
LD8.3.3-PL3.6.5-SNAPSHOT-b182-VLT1.5.3-b37-UHNS1.3.9-MCv1_8_R2-BNGE_false-SQL_false

PS: I plan using SQL when i have the server ready.

**Comment by dumbninja22** [comment]
Arena overlaps are detected by boundslow and boundshigh of the arenas overlapping another. Surly out of the infinite space in a MC world you can spare some more gap between 2 arenas?

Anyways, you can fix this by separating the arenas a little bit and making sure that the boundslow/boundshigh of two arenas do not overlap.

-Dumbninja22

**Comment by dumbninja22** [comment]
Reopening due to new evidence.

**Comment by dumbninja22** [comment]
OK I have a fix for this. Will release soon.
Simple issue is that the isInside util method ignored worlds.

Thank you for the report!
