### ISSUE TITLE
No pointer Exception Issue AGAIN

### ISSUE THREAD

**Issue by JHXSMatthew** [dumbninja22/UHNSBugTracker#21]
http://pastebin.com/zcGH0LiU

**Comment by JHXSMatthew** [comment]
It happens every game  under bungeemode.

 Support Code: LD8.6.5-PL3.6.5-SNAPSHOT-b196-VLT1.5.6-b49-UHNS1.4.7-MCv1_8_R3-BNGE_true-SQL_true

**Comment by dumbninja22** [comment]
Fixed in the new update.
