### ISSUE TITLE
Disguise block not visible when solid block

### ISSUE THREAD

**Issue by zedwick** [dumbninja22/UHNSBugTracker#29]
When I, as a hider, turn into a solid block I cannot see the block at all.
Only tested with just myself playing, so do not know if others can see me as a solid block.

LD8.6.5-PL3.6.4-VLTNULL-UHNS1.5.3B-MCv1_8_3R3-BNGE_true-SQL_false

**Comment by dumbninja22** [comment]
1) Bungee mode with the plugin requires MySQL and MySQL requires Bungee. Please enable or disable both of them.

2) Yeah, others will be able to see your solid block.

**Comment by zedwick** [comment]
Are you telling me that this issue is caused by not using MySQL with bungeecord?

I don't understand why I need to use MySQL to have a single standalone HideNSeek server connected to bungeecord.

**Comment by dumbninja22** [comment]
No, I just noticed you have those options enabled and my plugin is known to have issues with running in bungee mode without the help of SQL. Disable Bungee with the plugin. If you are running it and don't want cross-server join signs and stats, you can disable it and just run it as if you aren't even running bungee.

So basically, tell the plugin its not in a bungee environment by disabling bungee mode in the HNS config file and everything should be fine.
