### ISSUE TITLE
Arena information is lost when sqlEnabled: true

### ISSUE THREAD

**Issue by Deathinflames** [dumbninja22/UHNSBugTracker#3]
I just discovered a strange issue when setting up arenas and sqlEnabled: true.

Setting up the actual arenas works fine, however when it comes time to restart the server all arena information is lost and each arena will have to be re-made.

Support Code: https://i.gyazo.com/1e447e5f0b62e668f989bda2f024413d.png

**Comment by dumbninja22** [comment]
Looking at your support code you do not have bungee cord option enabled in the plugin config. MySQL requires Bungeecord. I'm locking this issue 
 - if there is anything else let me know on SpigotMC PM or create a new support ticket.
