### ISSUE TITLE
Shop problem & NullPointerException & Particle effects problem

### ISSUE THREAD

**Issue by enarkay** [dumbninja22/UHNSBugTracker#31]
1.The biggest problem I'm experiencing is that upon clicking <HIDER SKILLS> or <SEEKER UPGRADES> menu in shop, the GUI windows close and I'm simply exited out of the GUI. Is this an error, or am I supposed to set something up to access the inside of these menus? It was my understanding that items such as <DISGUISE SWAPPER> or <SHOCKERSWORD> were default shop items that just came along, without any additional setup. So either I am totally getting this wrong, or some error is preventing me from accessing the <HIDER SKILLS> and <SEEKER UPGRADES> menus and the items inside them. (The <DISGUISE SWAPPER> and <SHOCKERSWORD> are supposed to be inside them, no?)

2.The NullPointerException is something I noticed as I was trying to figure out the cause of the above problem. After I join an arena and as soon as I select one of the GUI items in my hotbar (not right-click them to open up their according GUIs, but just simply select the hotbar slot), the following error starts to appear repeatedly in my console:
![default](https://cloud.githubusercontent.com/assets/7910166/11586509/d852d396-9ab6-11e5-98fa-1f86a9f4df32.JPG)

Originally I just had Vault installed, as it was stated in your -IMPORTANT NOTES- that (only) Vault is required for the shop and kit function, but after experiencing the first problem I tried again with Craftconomy added but saw no difference in the problem. Which also leads me to another question, so if things were to work as you expected and you wanted to use the shop and kits function, is only Vault required or do you also need an economy plugin like Craftconomy in addition?

3.I turned the particle effects to false in the config, but whenever I apply an extra effect to a player other than the invisibility effect that naturally comes for a hider when he/she is fixed solid, the particle effects still show up.

Of course, I turned the particle effects off when I executed the effect command:
effect <playername> night_vision 1000000 0 true (true meaning particle effects should be hidden, just in case you're not too familiar with minecraft commands)

I'm not sure if you would be wondering what the necessity of applying an additional effect(s) to players in-game would be, but just in case you are, it's so that players can see in dark maps and I don't have to make maps ugly by placing down light sources here and there lol

here's my support code btw:
![default](https://cloud.githubusercontent.com/assets/7910166/11586606/a072e4d8-9ab7-11e5-9dea-f22fa5b38cf1.JPG)

**Comment by enarkay** [comment]
I am updating the status: I have solved problems 1) and 2).

So only problem 3) "particle effects from any additional effect other than the lock-on invisibility shows, even with particles turned off in the config and effect command applied without particles" remains

**Comment by dumbninja22** [comment]
The config particle disabler does not do anything to custom effects (just the plugin-generated effects), and I'm not sure it's possible to make a simple config option for that.


To add custom block names, create a file named "blockLang.yml" in the Ultimate Hide N Seek folder, then make the KEYS the technical name of the block and the VALUE the new name of the block. Example: http://pastebin.com/2sX6qu0z

**Comment by enarkay** [comment]
Okay, block translation is straight-forward and easy. Great! I will try it out asap.

As for the potion particles, it only happens once I'm inside an arena. For example, I would apply myself an infinite duration night_vision with no particles through a vanilla command and it would work as expected: infinite night_vision, and no particles. But whenever I'm inside an arena, having night_vision effect causes particles around players, thereby potentially exposing hiders in their spots.

I will also go ahead and fiddle with combinations of plugins and this and that to see if something else may be causing the problem, although the only 3 plugins I have on the server at the moment is HideNSeek, Vault, and Craftconomy so don't see much chance in something else being the problem.

I also came up with some more suggestions but am wondering if I should continue on here, or open up a separate issue and make the suggestions. Which way should I go? Also, I read the guidelines for making suggestions or reporting bugs/issues but I simply don't know how to TAG issues. So if I were to open up another issue for the purpose of making suggestions, how would I go about tagging it as SUGGESTIONS, or did I misunderstand something and tagging is something I can't do in the first place?

**Comment by dumbninja22** [comment]
I just released an update that may help with potion particles. After this update, just make sure you use TRUE in the command when giving the player the potion and it should work.

You can go ahead and create one issue for all your suggestions, name it like"<NAME>'s suggestion list". To tag issues simply type hashtag and the number of the issue, like #29
