### ISSUE TITLE
Pig Bug

### ISSUE THREAD

**Issue by CzEMC** [dumbninja22/UHNSBugTracker#33]
**What Happened**
Everything's normal when the were in the lobby and while the game starts, however, the seekers are pigs only. I noticed that there were many errors in the logs.

**What we did for a run though**
I started the server, logged in with me and my alt. I played a game. Stopped the server.

Paste bin: http://pastebin.com/mdbPEwHk

Support Code: LD8.2.6-SNAPSHOT-PL3.6.4-VLT1.5.3-b37-UHNS1.5.5-MCv1_7_R4-BNGE_false-SQL_false

Thank you for your time!

**Comment by dumbninja22** [comment]
Can you update to 1.8?

**Comment by CzEMC** [comment]
Well, I like my entire network to remain 1.7-1.8 compatible. Is there any way I can stay on 1.7?

**Comment by dumbninja22** [comment]
Maybe. I think the issue is I'm using 1.8 potions and stuff.

**Comment by dumbninja22** [comment]
FYI I am working on this today.

**Comment by dumbninja22** [comment]
Posted a new update. If you still have the issue, create a new support ticket here and provide more information and screenshots.
