### ISSUE TITLE
Sign doesn't work

### ISSUE THREAD

**Issue by anemul** [dumbninja22/UHNSBugTracker#34]
Sign does not work , I can not join game . Spigot website mentions NinjagamesAPI , but no such file on my server that I can find .

LD8.6.5PL3.6.4-VLT1.5.6-b49-UHNS1.5.5-MCV1_8_R2-BNGE_false-SQL_false

**Comment by dumbninja22** [comment]
Ninja games API is nothing  to worry about. It is just saying that you do not need other MiniGame APIs in order for the game to run. 

Regarding signs, I need 3 things:
1) any errors in console? 

2) do you get a message in the chat when you try to create a sign? 

3) how are you creating the signs? What are you typing in them? Screenshot if possible.

**Comment by anemul** [comment]
No errors
No messages
[Hide N Seek]
FindMe
-block-
with and without that last part .
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by anemul** [comment]
I did find some errors in the server terminal :

**Comment by anemul** [comment]
So how goes it ?

**Comment by dumbninja22** [comment]
Did you create the arena with the exact name "FindMe"? Capitalization matters. It has to be "FindMe" exactly like that.

The errors would help.

**Comment by anemul** [comment]
Yes I did


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by anemul** [comment]
Are there suppose to be spaces in > [Hide N Seek] ?

**Comment by dumbninja22** [comment]
Yes, spaces. 

No brackets.

**Comment by anemul** [comment]
I tried it both ways . I am going to do a clean install of it today , I will send you logs of everything I get , if I run into the same thing again .

**Comment by anemul** [comment]
OK New fresh install went well . This time around We was able to use the sign to join , everything worked well up until the game was over and the game on the sign said starting and when we typed /hns leave or /hns leave FindMe , it said we were not in an arena . Here is a pic of that . The server threw some errors and I will send the logfile from the server in just a minute .

**Comment by anemul** [comment]
Sorry couldn't get the uploader on the site to work .
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by anemul** [comment]
Here is the log from todays install .

[latest.log.zip](https://github.com/dumbninja22/UHNSBugTracker/files/74185/latest.log.zip)

**Comment by anemul** [comment]
Here is pic of sign . Hopefully
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by dumbninja22** [comment]
How many players were in the game when you got the errors?

**Comment by dumbninja22** [comment]
Also I need you to go in messages.yml, open it with notepad
Press CTRL + H
For "Find what", input "|%money%" (without quotes)
For "Replace wth", clear the text field (leave it blank)

Hit "Replace All".

Save it. Make sure your server is using the updated messages.yml file.

**Comment by anemul** [comment]
2
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by dumbninja22** [comment]
Okay, follow the instructions in the previous post I made, right before you commented.

**Comment by anemul** [comment]
by the way I am running my server on a Mint Linux box . But I did as you
said and logged back in and the sign has not changed . I am going to try
and remake sign .

**Comment by anemul** [comment]
Now it says there are no arenas on the server . I will remake :(

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by dumbninja22** [comment]
After you remake, let me know if you can play a game without errors. If you still run into issues, tell me the IP and I'll join the server to help.

**Comment by anemul** [comment]
OK done as you said and the result is the same . except it didn't throw as
much of an error list I don't think , here is the new log file .

**Comment by anemul** [comment]
24.243.161.184 is IP
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by anemul** [comment]
a new development . With HNS installed and after the messages.yml edit , I
noticed I couldn't break anything in any world even as op/admin , I removed
HNS and now am able to break things again in all worlds .

**Comment by anemul** [comment]
Yep , when I put the jar and files back in and delte messages.yml so I get
a replacement file , I can dig and build . The game will star but it is as
the first time .stop server and change messages.yml as directed and game
starts , disguises are invisible to the hider , but after game , sign does
same old thing and I can no longer dig or build . /hns stop FindMe did not
seem to have any effect either .

**Comment by dumbninja22** [comment]
I am on the server now..

**Comment by anemul** [comment]
[latest3.log.zip](https://github.com/dumbninja22/UHNSBugTracker/files/74385/latest3.log.zip)

**Comment by dumbninja22** [comment]
Solved by removing Vault. Next update I will look into whats wrong with economy detection.

If you have any more problems just create a new issue :)
