### ISSUE TITLE
Game dosent reload properly and Hiders player not invisable

### ISSUE THREAD

**Issue by zobos** [dumbninja22/UHNSBugTracker#36]
When I am playing and the game ends all the blocks that players morphed into stay in the map and dont reset

also when players become a solid block there skin and name tag is still visible

![capture](https://cloud.githubusercontent.com/assets/8007359/12374006/13d8fb34-bc86-11e5-92c6-6381c0f23cb9.PNG)

**Comment by dumbninja22** [comment]
Install Lib's Disguises and ProtocolLib - those plugins are needed for the game to work. Vault is also recommended.
