### ISSUE TITLE
Add No weather under BungeeMode

### ISSUE THREAD

**Issue by JHXSMatthew** [dumbninja22/UHNSBugTracker#8]
Some minor things may add to bungeeMode Thus the plugin would actually takes control of the server.
Since bungeeMode really means dedicated Game mode.

No Weather change.
Always day.

![image](https://cloud.githubusercontent.com/assets/11565658/9834714/05393c34-5a0b-11e5-8445-5e5b1705c6e7.png)

**Comment by dumbninja22** [comment]
Added in 1.4.6
